context:
  name: dynare-preprocessor-pylib
  version: 0.0.0.dev1

package:
  name: dynare-preprocessor-pylib
  version: 0.0.0.dev1

source:
  url: https://github.com/EconForge/dynare_preprocessor_pylib/archive/79fa5730d7f1300109ec36900f3241c0527e32c7.tar.gz
  sha256: 66863669aa9ea09c431f28eaabe41d574a758425db77605d52edfb9ff040a038

build:
  number: 3
  skip:
    - osx
    
requirements:
  build:
    - '${{ compiler("cxx") }}'
    - python
    - if: unix
      then: flex
    - if: unix
      then: bison
    - if: win
      then: winflexbison
    - meson
    #    - cross-python_emscripten-wasm32 # only for wasm
    - pkg-config

  host:
    - python
    - pybind11
    - libboost-headers
    # - pthread-stubs   # all threading removed from source

  run:
    - python

tests:
  - python:
      imports:
        - dynare_preprocessor
  - script:
      - pytest run_test.py
    requirements:
      run:
        - pytest
    files:
      recipe:
        - run_test.py


about:
  homepage: https://www.dynare.org/
  summary: Dynare preprocessor
  description: Preprocessor for Dynare, a platform for handling a wide class of economic models.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - albop
