context:
  name: dynare-preprocessor-pylib
  version: 0.0.0.dev1

package:
  name: dynare-preprocessor-pylib
  version: 0.0.0.dev1

source:
  url: https://git.dynare.org/albop/preprocessor/-/archive/dynare_lite/preprocessor-dynare_lite.tar.gz
  sha256: a712547f2c57a8f8a683dd0f8cf8d28ab8083f4523ecb519dad5ffb35541d69f

build:
  number: 1
  skip:
    - win
    - osx

requirements:
  build:
    - '${{ compiler("cxx") }}'
    - python
    - bison
    - flex
    - meson
    #    - cross-python_emscripten-wasm32 # only for wasm
    - pkg-config

  host:
    - python
    - pybind11
    - libboost-headers
    # - pthread-stubs   # all threading removed from source

  run:
    - python

tests:
  - python:
      imports:
        - dynare_preprocessor
  - script:
      - pytest run_test.py
    requirements:
      run:
        - pytest
    files:
      recipe:
        - run_test.py


about:
  homepage: https://www.dynare.org/
  summary: Dynare preprocessor
  description: Preprocessor for Dynare, a platform for handling a wide class of economic models.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - albop
