context:
  name: dynare-preprocessor-pylib
  version: 0.0.1.dev0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/EconForge/dynare_preprocessor_pylib/archive/073de0045c4a1b986081fc4164c290d7de510c85.tar.gz
  sha256: 594241ecd8e48f8d52f96875fd2c5a80dca7899148f4e772fd45b6ab99d6056e

build:
  number: 0

requirements:
  build:
    - '${{ compiler("cxx") }}'
    - '${{ stdlib("c") }}'
    - python
    - nanobind
    - if: unix
      then: flex
    - if: unix
      then: bison
    - if: win
      then: winflexbison
    - meson
    - ninja
    - pkg-config

  host:
    - python
    - nanobind
    - libboost-headers

  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - dynare_preprocessor
  - script:
      - pytest run_test.py
    requirements:
      run:
        - pytest
    files:
      recipe:
        - run_test.py

about:
  homepage: https://www.dynare.org/
  summary: Dynare preprocessor
  description: Preprocessor for Dynare, a platform for handling a wide class of economic models.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - albop
