context:
  name: dynare-preprocessor-pylib
  version: 0.0.1

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/EconForge/dynare_preprocessor_pylib/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a3b0e13ae1917607427c0fd47f4e45e992a4715000df0fc2a02b8d8fb30851d1

build:
  number: 1

requirements:
  build:
    - '${{ compiler("cxx") }}'
    - '${{ stdlib("c") }}'
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
    - python
    - nanobind
    - if: unix
      then:
        - flex
        - bison
    - if: win
      then: winflexbison
    - meson
    - ninja
    - pkg-config

  host:
    - python
    - nanobind
    - libboost-headers

  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - dynare_preprocessor
  - script:
      - pytest run_test.py
    requirements:
      run:
        - pytest
    files:
      recipe:
        - run_test.py

about:
  homepage: https://www.dynare.org/
  summary: Dynare preprocessor
  description: Preprocessor for Dynare, a platform for handling a wide class of economic models.
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - albop
